branch-defaults:
  master:
    environment: dev-env
    group_suffix: null
environment-defaults:
  dev-env:
    branch: null
    repository: null
global:
  application_name: teste-eb
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: PHP 7.1
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
